mappings:
  - source: bin/dotfiles
    target: .local/bin/dotfiles
  - source: git/gitconfig
    target: .gitconfig
  - source: git/gitignore
    target: .gitignore
  - source: git/gitmessage
    target: .gitmessage
  - source: git/ignore
    target: .config/git/ignore
  - source: zsh/zshrc
    target: .zshrc
  - source: zsh/zprofile
    target: .zprofile
  - source: config/nvim/init.lua
    target: .config/nvim/init.lua
  - source: config/nvim/lua/options.lua
    target: .config/nvim/lua/options.lua
  - source: config/nvim/lua/keymaps.lua
    target: .config/nvim/lua/keymaps.lua
  - source: config/nvim/lua/plugins.lua
    target: .config/nvim/lua/plugins.lua
  - source: config/nvim/lua/autocmds.lua
    target: .config/nvim/lua/autocmds.lua
  - source: config/ghostty/config
    target: .config/ghostty/config
  - source: tmux/tmux.conf
    target: .tmux.conf
  - source: ruby/irbrc
    target: .irbrc
  - source: ruby/pryrc
    target: .pryrc
  - source: config/psqlrc
    target: .psqlrc
  - source: cursor/commands
    target: .cursor/commands
